inputs:
  project-root:
    required: false
    default: '.'
runs:
  using: composite
  steps:
    - name: Disable IPv6
      shell: bash
      run: |
        echo "Disabling IPv6..."
        # Use tee instead of sysctl
        echo 1 | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6
        echo 1 | sudo tee /proc/sys/net/ipv6/conf/default/disable_ipv6
        echo 1 | sudo tee /proc/sys/net/ipv6/conf/lo/disable_ipv6
        
        # Verify IPv6 status
        echo "Current IPv6 status:"
        cat /proc/sys/net/ipv6/conf/all/disable_ipv6
        cat /proc/sys/net/ipv6/conf/default/disable_ipv6
      working-directory: ${{ inputs.project-root }}

    - name: Check IPv6 Status
      shell: bash
      run: |
        echo "=== IPv6 Kernel Parameters ==="
        cat /proc/sys/net/ipv6/conf/all/disable_ipv6
        cat /proc/sys/net/ipv6/conf/default/disable_ipv6
        cat /proc/sys/net/ipv6/conf/lo/disable_ipv6
        
        echo -e "\n=== Network Interfaces IPv6 Status ==="
        ip -6 addr
        
        echo -e "\n=== Active Internet Connections (including servers) ==="
        netstat -tuln | grep -i ":::"
        
        echo -e "\n=== Testing IPv6 Connectivity ==="
        ping6 -c 1 google.com || echo "IPv6 ping failed - IPv6 likely disabled"
