inputs:
  project-root:
    required: false
    default: '.'
runs:
  using: composite
  steps:
    - name: Run prefer IPv4 script
      shell: bash
      run: force-ipv4.sh
      working-directory: ${{ inputs.project-root }}
