inputs:
  project-root:
    required: false
    default: '.'
runs:
  using: composite
  steps:
    - name: Disable IPv6
      shell: bash
      run: |
        echo "Disabling IPv6..."
        # Use tee instead of sysctl
        echo 1 | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6
        echo 1 | sudo tee /proc/sys/net/ipv6/conf/default/disable_ipv6
        echo 1 | sudo tee /proc/sys/net/ipv6/conf/lo/disable_ipv6
        
        # Verify IPv6 status
        echo "Current IPv6 status:"
        cat /proc/sys/net/ipv6/conf/all/disable_ipv6
        cat /proc/sys/net/ipv6/conf/default/disable_ipv6
      working-directory: ${{ inputs.project-root }}
