inputs:
  project-root:
    required: false
    default: '.'
runs:
  using: composite
  steps:
    - name: Make script executable
      shell: bash
      run: chmod +x ${{ github.action_path }}/force-ipv4.sh

    - name: Run IPv4 script
      shell: bash
      run: sudo ${{ github.action_path }}/force-ipv4.sh
      working-directory: ${{ inputs.project-root }}
