name: Workflow which determines, what should be built on strapi/next projects
on:
  workflow_call:
    inputs:
      runs-on:
        description: "Define the type of machine to run the job on"
        type: string
        required: false
        default: "bratislava"
    outputs:
      strapi:
        description: "Returns true if strapi can be built"
        value: ${{ jobs.conditions.outputs.strapi }}
      next:
        description: "Returns true if next can be built"
        value: ${{ jobs.conditions.outputs.next }}
jobs:
  changes:
    name: Checking for directory changes in repository
    runs-on: ${{inputs.runs-on}}
    outputs:
      strapi: ${{ steps.filter.outputs.strapi }}
      next: ${{ steps.filter.outputs.next }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 2

      - name: Pipelines Version
        run: |
          echo "Pipelines version: 2.4.0"

      - uses: dorny/paths-filter@0e4a8c6effa4802afeda77dc8d303f8176d7dfad # v3.0.4
        id: filter
        with:
          filters: |
            strapi:
              - 'strapi/**'
            next:
              - 'next/**'
  conditions:
    name: Checking build conditions
    needs: changes
    runs-on: ${{inputs.runs-on}}
    env:
      COUNT: 0
    outputs:
      strapi: ${{ steps.strapi.outputs.condition }}
      next: ${{ steps.next.outputs.condition }}
    steps:
      - id: strapi
        name: Check for build strapi
        if: needs.changes.outputs.strapi == 'true'
        run: |
          echo "COUNT=$(($COUNT+1))" >> $GITHUB_ENV
          echo "condition=true" >> $GITHUB_OUTPUT

      - id: next
        name: Check for build next
        if: needs.changes.outputs.next == 'true'
        run: |
          echo "COUNT=$(($COUNT+1))" >> $GITHUB_ENV
          echo "condition=true" >> $GITHUB_OUTPUT

      - id: conditions-count-zero
        name: Checking if there is only zero condition true
        if: env.COUNT == 0
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            core.notice(':heavy_exclamation_mark: We have zero builds based on conditions. Exiting pipeline.')
