name: General workflow which builds image from source using bratiska-cli.
on:
  workflow_call:
    inputs:
      directory:
        description: 'A Folder within the repository where things should be build.'
        default: '/'
        required: false
        type: string
      debug:
        description: 'Debug flag'
        default: ''
        required: false
        type: string
      version:
        description: 'Bratiska-cli version'
        default: 'stable'
        required: false
        type: string
      build_image_no_registry:
        description: 'If you want to build image without registry.'
        default: '--build_image_no_registry'
        required: false
        type: string
      registry:
        description: 'Registry where should be built images stored'
        default: 'harbor.bratislava.sk'
        required: false
        type: string
      username:
        description: 'Docker username'
        default: 'robot$github_actions'
        required: false
        type: string
      tag:
        description: 'Tag for the build image'
        default: ''
        required: false
        type: string
      build_arg:
        description: 'Defining build arg for Dockerfile'
        default: ''
        required: false
        type: string

    secrets:
      sentry-token:
        description: 'Token used for sentry debugging.'
        required: false
      registry-pass:
        description: 'Password for registry.'
        required: false

jobs:
  build-with-bratiska-cli:
    name: Build with bratiska-cli
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    steps:
      - name: Checking out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pipelines Version
        run: |
          echo "Pipelines version: 2.3.0"

      - name: Directory check
        run: pwd

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Check for Secret availability
        id: secret-check
        shell: bash
        run: |
          if [ "${{ secrets.registry-pass }}" != '' ]; then
          echo "available=true" >> $GITHUB_OUTPUT;
          else
          echo "available=false" >> $GITHUB_OUTPUT;
          fi

      - name: Login to Harbor
        if: ${{ steps.secret-check.outputs.available == 'true' }}
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.registry-pass }}

      - name: Print pipeline summary
        run: |
          echo "### Bratiska-cli is building:" >> $GITHUB_STEP_SUMMARY
          echo ":arrow_right: Project folder: **${{ inputs.directory }}**" >> $GITHUB_STEP_SUMMARY

      - name: Install Prerequisites -  Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installing Bratiska-cli version
        run: yarn global add bratislava/bratiska-cli#${{ inputs.version }}

      - name: Running git fetch for Bratiska-cli
        run: git fetch

      - name: Print Bratiska-cli version
        run: bratiska-cli --version

      - name: Running build with Bratiska-cli
        run: bratiska-cli build_image --env=staging ${{ inputs.build_image_no_registry }} ${{ inputs.tag }} ${{ inputs.build_arg }} ${{ inputs.flag }} --sentry=${{ secrets.sentry-token }} ${{ inputs.debug }}
        continue-on-error: false

      - name: Print pipeline summary - image build
        run: |
          echo ":partying_face: Bratiska-cli successfully built an image from path: ${{ inputs.directory }}" >> $GITHUB_STEP_SUMMARY

      - name: Print pipeline comment - image build
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2.9.0
        with:
          header: Build Conditions
          append: true
          message: |
            :partying_face: Bratiska-cli successfully built an image from path: ${{ inputs.directory }}
