name: Workflow which detects what helm instance should be deployed
on:
  workflow_call:
    outputs:
      instance:
        description: "Returns value of instance"
        value: ${{ jobs.conditions.outputs.dev }}
jobs:
  conditions:
    name: Checking deployment conditions
    runs-on: ubuntu-latest
    env:
      COUNT: 0
    outputs:
      instance: ${{ steps.clean.outputs.instance }}
    steps:

    - id: clean
      name: Clean tag name
      env:
        REF_NAME: ${{ github.ref_name }}
      run: |
        echo "TAG=${REF_NAME##*/}" >> $GITHUB_ENV

    - name: Print variable
      run: |
        echo ${{ env.TAG }}

    - id: split
      name: Split tag name
      env:
        TAG: ${{ env.TAG }}
      run: |
        echo "instance=${TAG##*-}" >> $GITHUB_OUTPUT

    - name: Print variable
      run: |
        echo ${{ steps.clean.outputs.instance }}