name: Print pipelines version
on:
  workflow_call:
    inputs:
      runs-on:
        description: 'Define the type of machine to run the job on'
        type: string
        required: false
        default: '["self-hosted", "Linux", "X64", "bratislava"]'

jobs:
  print_version:
    name: Print pipelines version
    runs-on: ubuntu-latest
    steps:
      - name: Version
        run: |
          echo "Pipelines version: 2.0.1"
          echo "Pipelines version: 2.0.1" >> $GITHUB_STEP_SUMMARY
