name: Print pipelines version
on:
  workflow_call

jobs:
  print_version:
    name: Print pipelines version
    runs-on: ubuntu-latest
    steps:
      - name: Version
        run: |
          echo "Pipelines version: 2.0.1"
          echo "Pipelines version: 2.0.1" >> $GITHUB_STEP_SUMMARY
