name: Validate nest-prisma code
on:
  workflow_call:
    inputs:
      runs-on:
        description: 'Define the type of machine to run the job on'
        type: string
        required: false
        default: '["self-hosted", "Linux", "X64", "bratislava"]'
      directory:
        description: "Where typescript have to be checked"
        type: string
        required: false
        default: './src'
      node:
        description: "Define node version"
        type: string
        required: false
        default: '20'
      level:
        description: "Change reporter level if you need"
        type: string
        required: false
        default: 'warning'

jobs:
  test:
    name: Unit tests
    runs-on: ${{fromJSON(inputs.runs-on)}}
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pipelines Version
        run: |
          echo "Pipelines version: 2.3.0"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci
      - run: cp .env.example .env
      - run: npx prisma generate

      - name: Run unit tests
        run: npm run test

  lint:
    name: Code quality
    runs-on: ${{fromJSON(inputs.runs-on)}}
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci
      - run: cp .env.example .env
      - run: npx prisma generate

      - name: Typescript reviewdog check
        uses: EPMatt/reviewdog-action-tsc@v1.7.0
        # Review dog will fail when pull request has more than 300 changed files.
        # We want that next typescript check will do its job for all files
        continue-on-error: true
        with:
          # Change reviewdog reporter if you need
          # [github-pr-check,github-check,github-pr-review].
          # More about reviewdog reporters at
          # https://github.com/reviewdog/reviewdog#reporters
          reporter: github-check
          # Change reporter level if you need
          # [info,warning,error].
          # More about reviewdog reporter level at
          # https://github.com/reviewdog/reviewdog#reporters
          level: ${{inputs.level}}
          workdir: ${{ inputs.directory }}

      - name: Typescript check
        run: npx tsc

      - name: ESlint check
        run: npm run lint
