name: Validate nest-prisma code
on:
  workflow_call:
    inputs:
      runs-on:
        description: "Define the type of machine to run the job on"
        type: string
        required: false
        default: "bratislava"
      directory:
        description: "Base dir where whole app is located."
        type: string
        required: false
        default: "./"
      typescript-directory:
        description: "Where typescript have to be checked"
        type: string
        required: false
        default: "./src"
      node:
        description: "Define node version"
        type: string
        required: false
        default: "20"
      level:
        description: "Change reporter level if you need"
        type: string
        required: false
        default: "warning"

jobs:
  test:
    name: Unit tests
    runs-on: ${{inputs.runs-on}}
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Pipelines Version
        run: |
          echo "Pipelines version: 2.4.0"

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "20"
          package-manager-cache: false

      - run: npm ci
      - run: cp .env.example .env
        continue-on-error: true
      - run: npx prisma generate

      - name: Run unit tests
        run: npm run test

  lint:
    name: Code quality
    runs-on: ${{inputs.runs-on}}
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "20"
          package-manager-cache: false

      - run: npm ci
      - run: cp .env.example .env
      - run: npx prisma generate

      - name: Typescript reviewdog check
        uses: EPMatt/reviewdog-action-tsc@63d923a3c5b4497671940b8874f58a404e2351b5 # v1.11.0
        # Review dog will fail when pull request has more than 300 changed files.
        # We want that next typescript check will do its job for all files
        continue-on-error: true
        with:
          # Change reviewdog reporter if you need
          # [github-pr-check,github-check,github-pr-review].
          # More about reviewdog reporters at
          # https://github.com/reviewdog/reviewdog#reporters
          reporter: github-check
          # Change reporter level if you need
          # [info,warning,error].
          # More about reviewdog reporter level at
          # https://github.com/reviewdog/reviewdog#reporters
          level: ${{inputs.level}}
          workdir: ${{ inputs.typescript-directory }}

      - name: Typescript check
        run: npx tsc

      - name: ESlint check
        run: npm run lint
